services:
  redis-master:
    container_name: redis-master
    image: 'bitnami/redis:latest'
    volumes:
      - "./data/master:/data"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  redis-slave-1:
    container_name: redis-slave-1
    image: 'bitnami/redis:latest'
    volumes:
      - "./data/slave_1:/data"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    depends_on:
      - redis-master

  redis-slave-2:
    container_name: redis-slave-2
    image: 'bitnami/redis:latest'
    volumes:
      - "./data/slave_2:/data"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6381:6379"
    depends_on:
      - redis-master