services:
  es-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es-node-1
    environment:
      - node.name=es-node-1
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node-2
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - es-data-1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es-network
    restart: always

  es-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es-node-2
    environment:
      - node.name=es-node-2
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node-1
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - es-data-2:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - es-network
    restart: always

networks:
  es-network:
    driver: bridge

volumes:
  es-data-1:
    driver: local
  es-data-2:
    driver: local
