services:
  mysql-primary:
    image: mysql:8.0
    container_name: mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    volumes:
      - mysql-primary-data:/var/lib/mysql
      - ./primary-init:/docker-entrypoint-initdb.d
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=true
      --log-slave-updates=true
      --default-authentication-plugin=mysql_native_password

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    networks:
      - mysql_network
    volumes:
      - mysql-replica-data:/var/lib/mysql
      - ./replica-init:/docker-entrypoint-initdb.d
    depends_on:
      - mysql-primary
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --relay-log=relay-bin
      --read-only=true
      --gtid-mode=ON
      --enforce-gtid-consistency=true
      --log-slave-updates=true
      --default-authentication-plugin=mysql_native_password

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql-primary-data:
  mysql-replica-data:
